---
- name: "init | permanent disable selinux"
  selinux:
    state: disabled

- name: "init | permanent stop firewalld"
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: "init | install software"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ preinstall_packages }}"
  ignore_errors: true


    
