server:
  port: 8090  # default port 8080
  server_ip: 10.151.3.84  # default 127.0.0.1/localhost
  token_expire: 60  # default 30 minutes
databaseSource:
  username: root
  password: UVlY88m9suHLsthK
  ip: 10.151.3.84
  port: 3306
  database: demo2
  driver: mysql
  charset: utf8mb4
  loc: Asia/Shanghai
