---
# Variables here are applicable to all host groups
# hostname: k8s-test-67


#################################### init environment #################################
ntpserver: 'ntp.api.bz'
IP: "{{ ansible_eth0['ipv4']['address'] }}"

bin_dir: /usr/bin


#--------------- offline repos ---------------
repos:
  local: disable  #enable/disable
  package_path: /tmp/sensenebula-guard-1.0
  yum:
    domain: infra.yum.com
    repo_10: 10.5.6.10:6000
    port: 7000
    data: /data/yum_data

  docker:
    data: /data/docker-registry/
    port: 5000

  helm:
    name: chartmuseum
    data: /data/charts
    port: 8080
    package: helm_charts/charts_package

py3:
  off_line: enable
#---------------------------------------------


docker_registry: 10.5.6.10

#kernel_update_version: 3.10.0-693.5.2.el7.x86_64

#################################### kubernetes vars ####################################
docker_ce_version: 'docker-ce-18.06.1.ce-3.el7'
docker_cgroup_driver: 'systemd'
docker_insecure_registry:
  - 192.168.0.0/24
#docker_default_runtime: 'nvidia'
#docker_daemon_graph: '/var/lib/docker'

#kube_config_dir: /etc/kubernetes
