---
# Variables here are applicable to all host groups
# hostname: k8s-test-67


#################################### init environment #################################
ntpserver: 'ntp.api.bz'
IP: "{{ ansible_eth0['ipv4']['address'] }}"
# IP: {{ ansible_default_ipv4.address }}

bin_dir: /usr/bin
files_dir: ~/k8s  #拷贝临时存放文件路径，如dashboard.yaml k8s.sh等文件.


#--------------- offline repos ---------------
repos:
  local: disable  #enable/disable
  package_path: /tmp/sensenebula-guard-1.0
  yum:
    domain: infra.yum.com
    repo_10: 10.5.6.10:6000
    port: 7000
    data: /data/yum_data

  docker:
    data: /data/docker-registry/
    ip: "{{ IP }}"  #这里得确认是哪台机器作为离线仓库，是本地，还是其他的局域网机器. kubernetes/defaults/main.yaml引用了.
    port: 5000

  helm:
    name: chartmuseum
    data: /data/charts
    port: 8080
    package: helm_charts/charts_package

py3:
  off_line: enable
#---------------------------------------------


docker_registry: 10.5.6.10

#kernel_update_version: 3.10.0-693.5.2.el7.x86_64

#################################### kubernetes vars ####################################
# docker_ce_version: 'docker-ce-18.06.1.ce-3.el7'
docker_ce_version: 'docker-ce-18.09.4-3.el7'
docker_cgroup_driver: 'systemd'
docker_insecure_registry:
  - 192.168.0.0/24
# docker_default_runtime: 'nvidia'
# docker_daemon_graph: '/var/lib/docker'

kube_tools_version: '1.14.0-0'  #kubelet kubectl kubeadm

k8s_version:
  # v1.14.0 versions可以去此地址看: https://www.kubernetes.org.cn/5213.html
  kube: 'v1.14.0'  #images version and kubeadm init version
  # coredns: '1.2.6'
  coredns: '1.3.1'
  # etcd: '3.2.24'
  etcd: '3.3.10'
  pause: '3.1'
  
  flannel_amd64: 'v0.10.0-amd64'
  kubernetes_dashboard_amd64: 'v1.10.1'
  # tiller: v2.13.1  #这个是k8s v1.14.0版本的tiller，暂时没找到下载镜像地址，所以用下面旧地址.
  tiller: 'v2.11.0'

  traefik: '1.7.9'
  metircs_server_adm64: 'v0.3.1'
  addon_resizer: '1.8.4'

kube_proxy_mode: ipvs

kube_config_dir: /etc/kubernetes

iface: eth0









