---
{% if deploy_mode == "standalone" %}
hostAliases:
  - ip: "{{ license_ca.master }}"
    hostnames:
      - "private.ca.sensetime.com"
  - ip: "127.0.0.1"
    hostnames:
      - "slave.private.ca.sensetime.com"
{% endif %}

{% if deploy_mode == "distributed" %}
hostAliases:
  - ip: "{{ license_ca.master }}"
    hostnames:
      - "private.ca.sensetime.com"
  - ip: "{{ license_ca.slave }}"
    hostnames:
      - "slave.private.ca.sensetime.com"

replicaCount: 3
{% endif %}
