server:
  port: 8090  # default port 8080
  server_ip: 127.0.0.1  # default 127.0.0.1/localhost
  token_expire: 60  # default 30 minutes
databaseSource:
  username: root
  password: rock1314  # UVlY88m9suHLsthK
  ip: 10.151.3.86
  port: 3333  # default port 3306
  database: demo2
  driver: mysql
  charset: utf8mb4
  loc: AsiaShanghai
